# Docs: <https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/customizing-dependency-updates>

version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - internal
    commit-message:
      prefix: chore
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: docker
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - internal
    commit-message:
      prefix: chore
    groups:
      docker:
        patterns:
          - '*'

  - package-ecosystem: npm
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - internal
    commit-message:
      prefix: chore
    groups:
      # Group all non-major updates together to reduce noise
      npm-minor-patch:
        update-types:
          - minor
          - patch
      # Major updates are ungrouped so they get individual review
