name: Cloudflare Infra

on:
  pull_request:
    paths:
      - 'infra/web/**'
      - '.github/workflows/cloudflare-web-deploy.yml'
      - '.github/actions/prepare-tofu/**'
      - '.github/actions/setup/**'
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.TF_CLOUDFLARE_API_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_VAR_workers_message: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.event.head_commit.message || github.sha }}
  TF_VAR_account_id: ${{ secrets.TF_VAR_ACCOUNT_ID }}
  TF_VAR_zone_id: ${{ secrets.TF_VAR_ZONE_ID }}
  TF_HTTP_ADDRESS: ${{ secrets.TF_HTTP_ADDRESS }}
  TF_HTTP_LOCK_ADDRESS: ${{ secrets.TF_HTTP_LOCK_ADDRESS }}
  TF_HTTP_UNLOCK_ADDRESS: ${{ secrets.TF_HTTP_UNLOCK_ADDRESS }}
  TF_HTTP_USERNAME: ${{ secrets.TF_HTTP_USERNAME }}
  TF_HTTP_PASSWORD: ${{ secrets.TF_HTTP_PASSWORD }}
  TF_HTTP_LOCK_METHOD: 'POST'
  TF_HTTP_UNLOCK_METHOD: 'DELETE'
  TF_HTTP_RETRY_WAIT_MIN: '5'

concurrency:
  group: cloudflare-infra
  cancel-in-progress: false

jobs:
  plan:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: infra/web
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Prepare OpenTofu deployment
        uses: ./.github/actions/prepare-tofu

      - name: Comment PR plan
        uses: dflook/tofu-plan@3f5dc358343fb58cd60f83b019e810315aa8258f # v2.2.3
        with:
          path: infra/web
          label: production

  apply:
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/sable/v')) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: infra/web
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Prepare OpenTofu deployment
        uses: ./.github/actions/prepare-tofu

      - name: Plan infrastructure
        run: tofu plan -input=false -no-color

      - name: Apply infrastructure
        run: tofu apply -input=false -auto-approve
