name: Quality checks

on:
  pull_request:
  push:
    branches: [dev]
  merge_group:

jobs:
  format:
    name: Format check
    runs-on: ubuntu-latest
    if: github.head_ref != 'release'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup app
        uses: ./.github/actions/setup

      - name: Check formatting
        run: pnpm run fmt:check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.head_ref != 'release'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup app
        uses: ./.github/actions/setup

      - name: Run ESLint
        run: pnpm run lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    if: github.head_ref != 'release'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup app
        uses: ./.github/actions/setup

      - name: Run TypeScript typecheck
        run: pnpm run typecheck --pretty false

  knip:
    name: Knip
    runs-on: ubuntu-latest
    if: github.head_ref != 'release'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup app
        uses: ./.github/actions/setup

      - name: Run Knip
        run: pnpm run knip

  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.head_ref != 'release'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup app and build
        uses: ./.github/actions/setup
        with:
          build: 'true'
